import GRDB
import Foundation

extension IG.DB {
    /// Instance wrapping any error generated by the database used for caching.
    ///
    /// Most `underlyingError`s will be returned from the SQLite database.
    public struct Error: IG.Error {
        public let type: Self.Kind
        public internal(set) var message: String
        public internal(set) var suggestion: String
        public internal(set) var underlyingError: Swift.Error?
        public internal(set) var context: [(title: String, value: Any)] = []
        
        internal init(_ type: Self.Kind, _ message: String, suggestion: String, underlying error: Swift.Error? = nil) {
            self.type = type
            self.message = message
            self.suggestion = suggestion
            self.underlyingError = error
        }
        
        /// A factory function for `.sessionExpired` API errors.
        /// - parameter message: A brief explanation on what happened.
        /// - parameter suggestion: A helpful suggestion on how to avoid the error.
        internal static func sessionExpired(message: String = Self.Message.sessionExpired, suggestion: String = Self.Suggestion.keepSession) -> Self {
            self.init(.sessionExpired, message, suggestion: suggestion)
        }
        
        /// A factory function for `.invalidRequest` database errors.
        /// - parameter message: A brief explanation on what happened.
        /// - parameter suggestion: A helpful suggestion on how to avoid the error.
        internal static func invalidRequest(_ message: String, underlying error: Swift.Error? = nil, suggestion: String) -> Self {
            self.init(.invalidRequest, message, suggestion: suggestion, underlying: error)
        }
        
        /// A factory function for `.callFailed` database errors.
        /// - parameter message: A brief explanation on what happened.
        /// - parameter suggestion: A helpful suggestion on how to avoid the error.
        internal static func callFailed(_ message: String, underlying error: Swift.Error? = nil, suggestion: String) -> Self {
            self.init(.callFailed, message, suggestion: suggestion, underlying: error)
        }
    }
}

extension IG.DB.Error {
    /// The type of Database error raised.
    public enum Kind: CaseIterable {
        /// The Database instance couldn't be found.
        case sessionExpired
        /// The request parameters given are invalid.
        case invalidRequest
        /// A database request was executed, but an error was returned by low-level layers.
        case callFailed
    }
    
    /// Namespace for messages reused over the framework.
    internal enum Message {
        static var sessionExpired: String { "The \(IG.DB.self) instance was not found." }
    }
    
    /// Namespace for suggestions reused over the framework.
    internal enum Suggestion {
        static var keepSession: String { "The \(IG.DB.self) functionality is asynchronous; keep around the \(IG.DB.self) instance while a response hasn't been received." }
        static var readDocumentation: String { "Read the request documentation and be sure to follow all requirements." }
        static var bug: String { "A unexpected error was encountered. Please contact the repository maintainer and attach this debug print." }
        static var reviewError: String { "Review the returned error and try to fix the problem." }
    }
}

extension IG.DB.Error: IG.ErrorPrintable {
    var printableDomain: String {
        return "Database Error"
    }
    
    var printableType: String {
        switch self.type {
        case .sessionExpired: return "Session expired"
        case .invalidRequest: return "Invalid request"
        case .callFailed:     return "Database call failed"
        }
    }
    
    public var debugDescription: String {
        var result = self.printableHeader
        
        if let contextString = self.printableContext {
            result.append(contextString)
        }
        
        if let underlyingString = self.printableUnderlyingError {
            result.append(underlyingString)
        }
        
        result.append("\n\n")
        return result
    }
}
